everything compiles and runs
bedamunk/Assignment3 pull request #3
Opened 2020-03-04 20:14 UTC by samallen2228

I think the implementation of the classes is obviously different, but the structure of objects and hierarchy looks good

2020-03-04 20:15 UTC, samallen2228 reviewed
I think most of the changes it's highlighting are just formatting differences... I didn't change any code or logic

2020-03-04 20:17 UTC, samallen2228 reviewed
although I think there are some missing required attributes like a car has a year but the car superclass is missing that

2020-03-06 03:26 UTC, bedamunk approved these changes

2020-03-06 03:48 UTC, bedamunk requested changes
have newer version than this but year is added there already after you gave a heads up.  Sorry, I didn't see there was a change submitted before I did other work on the files to just pull this in.

2020-03-06 03:49 UTC, closed without merging